training_zip: /project/6050199/ext-data/hcp1200/deriv/hippunfold_trainingdata_zip/trainingdata_HCP1200_modalities-all_v4reg.zip

brain_t1: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz

aparc_aseg: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/aparc+aseg.nii.gz

n_examples: 100
