training_zip: /project/6050199/ext-data/hcp1200/deriv/hippunfold_trainingdata_zip/trainingdata_HCP1200_modalities-all_v4reg.zip

brain_t1: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz

aparc_aseg: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/aparc+aseg.nii.gz


task: Task501_HippSynthHCP
trainer: nnUNetTrainerV2
architecture: 3d_fullres
checkpoint: model_best


n_examples: 15

nnunet_env:
  nnUNet_raw_data_base: 'nnunet_data/raw_data'
  nnUNet_preprocessed: 'nnunet_data/preprocessed'
  RESULTS_FOLDER: 'nnunet_data/trained_models'


nnunet_env_tmp:
  nnUNet_raw_data_base: 'nnunet_data/raw_data'
  nnUNet_preprocessed: '$SLURM_TMPDIR/preprocessed'
  RESULTS_FOLDER: 'nnunet_data/trained_models'

